trigger:
  name: gitopstrigger
  identifier: gitopstrigger
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: OperationsTechnology
  stagesToExecute: []
  projectIdentifier: ENZ
  pipelineIdentifier: cicdgitopspipeline
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: githubconnector
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: changedFiles
              operator: NotIn
              value: configs/git-generator-files-discovery/
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          actions: []
  inputYaml: |
    pipeline:
      identifier: cicdgitopspipeline
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: <+trigger.branch>
